### ISSUE TITLE
Right-clicking on file in browser pops up error...

### ISSUE THREAD

**Issue by eobet** [bradklingensmith/project-glue#3]
Error:
  Traceback (most recent call last):

  File "C:\Users\Robert\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Project GLUE\error_handling.py", line 117, in wrapped_fn
    return fn(a1, a2, *args, **kwargs)

  File "C:\Users\Robert\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Project GLUE\ui\file_rename_operator.py", line 38, in poll
    file_path = context_helpers.get_active_file_path(context)

  File "C:\Users\Robert\AppData\Roaming\Blender Foundation\Blender\4.0\scripts\addons\Project GLUE\context_helpers.py", line 37, in get_active_file_path
    context.active_file.id_type != 'NONE' or

  AttributeError: 'FileSelectEntry' object has no attribute 'id_type'

Environment:
  Blender Version: (4, 0, 2)
  Project Glue Version: (1, 0, 2)
  Operating System: Windows-10-10.0.19045-SP0
  
  Installed Addons:
    io_anim_bvh
    io_curve_svg
    io_mesh_stl
    io_mesh_uv_layout
    io_scene_fbx
    io_scene_gltf2
    io_scene_x3d
    cycles
    node_wrangler
    theme_editor
    viewport_vr_preview
    mesh_looptools
    EdgeFlow
    adjust_vertex_weights
    SmartObjectSelect
    hide_only_vertex_ver1-0-2
    placeReflection
    UvSquares-master
    NodeRelax-Blender-Addon-main
    all_material_list
    mesh_tesselator
    randomvertexcolors280
    Bake-to-Vertex-Color-master
    measureit
    MESHmachine
    CustomPivotPainter_v102
    io_export_blend
    STEPper
    magic_uv
    viewport-fps
    blender_visual_scripting_addon
    vertexforge
    masktools
    BlenderGIS-228
    omni_nucleus
    omni_panel
    umm2
    omni_optimization_panel
    omni_audio2face
    camCursorLock
    mesh_mesh_align_plus
    materials_utils
    physical-open-waters
    Project GLUE
  
  Blend Files in Glue Project:
    Not in a Glue Project

**Comment by eobet** [comment]
The error pops up regardless of what file you right click, and about 30 of these error message windows appear...

**Comment by bradklingensmith** [comment]
Good afternoon!

I just uploaded version 1.0.3 to Blender Marketplace, which should fix this issue for you. Let me know if you're still having problems with that version.

Thanks,
Brad

**Comment by eobet** [comment]
Thank you for the update!

Unfortunately, the errors did not go away but I discovered their cause: I had not created a Glue Project.

It would be nice if the add-on could fail a bit more gracefully if you missed this first step.

**Comment by bradklingensmith** [comment]
Hi @eobet,

Based on the debugging information above, that sounds like a different issue.

Can you confirm that with version 1.0.3 you still get an error? And if so, could you upload the debugging information from that error? 

I agree that the add-on shouldn't give error messages if you're not in a Glue project. However, in my local testing, it behaves fine for me when I'm not in a Glue project; the Glue options are simply grayed out, which is what I intended to happen in that situation.

Thanks,
-Brad

**Comment by eobet** [comment]
Hello!

Testing again today with 1.0.3 the options are indeed greyed out so there are no errors. 👍
